# netlify.toml
[build]  
  publish = "/dist/clientes-app"
  command = "npm install --force && ng build --prod"


# Configuração das regras de redirecionamento
[[redirects]]
  # Redireciona todas as solicitações para o index.html
  from = "/*"
  to = "/index.html"
  status = 200
