# netlify.toml
[build]
  base = "frontend"
  publish = "frontend/dist/clientes-app"
  command = "npm ci && ng build --prod"


# Configuração das regras de redirecionamento
[[redirects]]
  # Redireciona todas as solicitações para o index.html
  from = "/*"
  to = "/index.html"
  status = 200
